uavcan/equipment/gnss/1060.Fix.uavcan
uavcan/equipment/gnss/1063.Fix2.uavcan
uavcan/equipment/gnss/ECEFPosition.uavcan

Added draft for a new GNSS-message containing ECEF coordinate representation: 1063.Fix2.uavcan. In addition, a new field for a 3x3 covariance matrix is included: pos_vel_covariance. This describes the covariance between position and velocity. Since covariance matrices are symmetric, only the upper-right quadrant of the 6-by-6 matrix is required.
Fixes #9

Addition of ECEF coordinate frame for GNSS-message

---

uavcan/equipment/gnss/1063.Fix2.uavcan
uavcan/equipment/gnss/ECEFPositionVelocity.uavcan

@glennib @WickedShell This PR extends the recently added message type `uavcan.equipment.gnss.Fix2` with an ECEF velocity field for completeness. I am going to merge it tomorrow unless you find anything wrong with these changes.
The ECEF velocity is represented in meters per second as a float32 triplet.
Normally we shouldn't modify data types that have already been merged into master, but this time we can deviate for two reasons:
1. There has been no official release of the DSDL set yet.
2. The new Fix2 message type is not yet used in production (this will change in a week once we've released the new Zubax GNSS v2.2 which will support both Fix and Fix2).

Amended the new GNSS Fix2 message with ECEF velocity field

---

uavcan/equipment/ahrs/1002.MagneticFieldStrength2.uavcan

New message based on 1001.MagneticFieldStrength with new field sensor_id, which can be used if your node has more then one sensor.

Added message 1002.MagneticFieldStrength2.uavcan

---

uavcan/README.md
uavcan/navigation/2000.GlobalNavigationSolution.uavcan

A couple of minor changes here:
* More elaborate comments.
* The linear velocity, angular velocity, and the linear acceleration are all explicitly marked as belonging to the body frame. This is in accordance with the conventions widely adopted in robotics.
@EShamaev you can now commit directly to this repository.

Navigation message from Eugene Shamaev

---

uavcan/equipment/gnss/1063.Fix2.uavcan

See this discussion for background: https://groups.google.com/forum/#!topic/uavcan/D5ZcsvirrbI
This pull request does not introduce any changes to the actual data type definitions. It only affects the comments.
Paging @olliw42 @glennib @WickedShell.

Clarifications on the GNSS time bases in use

---

uavcan/equipment/air_data/1027.RawAirData.uavcan

This PR adds Raw Airspeed Data message for use in transmitting the differential pressure and temperature directly to Autopilot or any other consumer where it will be converted into True Airspeed.

Add raw airspeed differential press and temp message

---

uavcan/tunnel/2010.Broadcast.uavcan
uavcan/tunnel/63.Call.uavcan

reduce buffer from 1024 to 60 and add ChannelID for routing
This effects uavcan.tunnel.Broadcast and tunnel.Call
The buffer.size was reduced because 1024 is unnecessarily huge. For embedded systems that is too much to do on the fly on every packet.
The number 60 was chosen so that a whole packet could fit into a single CANfd frame.
ChannelID was chosen so that, in the case of a virtual tunnel, multiple paths could exist between nodes. That is, if we were to treat this as a virtual COM port, we could have 256 "COM ports" talking to any 256 on the other end.

Tunneling: reduce buffer and add ChannelID

---

.travis.yml
test.py
uavcan/internet/udp/500.HandleIncomingPacket.0.1.uavcan
uavcan/internet/udp/65510.OutgoingPacket.0.1.uavcan
uavcan/node/430.GetInfo.0.1.uavcan
uavcan/node/431.GetPorts.0.1.uavcan
uavcan/node/432.GetPortInfo.0.1.uavcan
uavcan/node/433.GetPortStatistics.0.1.uavcan
uavcan/node/434.GetTransportStatistics.0.1.uavcan
uavcan/node/435.ExecuteCommand.0.1.uavcan
uavcan/node/62805.Heartbeat.1.0.uavcan
uavcan/node/PortID.1.0.uavcan
uavcan/node/ServiceID.1.0.uavcan
uavcan/node/SubjectID.1.0.uavcan
uavcan/pnp/65534.NodeIDAllocationData.0.1.uavcan
uavcan/pnp/server/390.AppendEntries.1.0.uavcan
uavcan/pnp/server/62810.ClusterDiscovery.1.0.uavcan
uavcan/pnp/server/Entry.1.0.uavcan
uavcan/time/62804.Synchronization.1.0.uavcan

PyDSDL version 0.1.0 is out: https://github.com/UAVCAN/pydsdl (also available on PyPI)
PyDSDL can do clever checks as proposed here by @kjetilkjeka (using exactly that syntax): https://forum.uavcan.org/t/new-dsdl-directive-for-simple-compile-time-checks/190/13 (not yet described in the specification, soon to be)
I fully comprehended the value of static checks only when I started using them myself here: they helped me to uncover a bit alignment issue in the `PortID` definition, which I promptly fixed. Luckily, this is a staging branch, so breaking changes are still possible, otherwise it would be a problem. Also, it is no longer necessary to go over each definition meticulously adding bits together to make sure everything is aligned properly, which is a really huge relief: you can just …

Assertion checks, CI is back

---

uavcan/pnp/65534.NodeIDAllocationData.0.1.uavcan
uavcan/pnp/65535.NodeIDAllocationDataMTU8.0.1.uavcan

The transport doesn't matter, MTU does. Updated the comments accordingly.

Renamed the CAN2.0-optimized allocation message

---

uavcan/diagnostic/65520.Record.1.0.uavcan
uavcan/file/405.GetInfo.0.1.uavcan
uavcan/file/406.ListDirectory.0.1.uavcan
uavcan/file/407.Modify.1.0.uavcan
uavcan/file/408.Read.1.0.uavcan
uavcan/file/409.Write.1.0.uavcan
uavcan/node/430.GetInfo.0.1.uavcan
uavcan/node/431.GetPorts.0.1.uavcan
uavcan/node/432.GetPortInfo.0.1.uavcan
uavcan/node/433.GetPortStatistics.0.1.uavcan
uavcan/node/434.GetTransportStatistics.0.1.uavcan
uavcan/node/PortID.1.0.uavcan
uavcan/pnp/server/390.AppendEntries.1.0.uavcan

I have updated the PyDSDL parser to require minor version as discussed here:
- https://github.com/UAVCAN/pydsdl/issues/5
- https://forum.uavcan.org/t/the-case-for-code-compatibility/194/12
The new PyDSDL version 0.2 is already released, which means that the CI in this repo will now require minor version as well.

Explicitly providing minor version for all nested types

---

uavcan/time/TimeSystem.0.1.uavcan

State explicitly that the TAI timestamp represents the number of SI time units (i.e., fixed length) elapsed since the midnight of 1 Jan 1970.

Resolve the TAI spec ambiguity

---

uavcan/internet/udp/32750.OutgoingPacket.0.1.uavcan

Users shouldn't have to roll their own crypto. UAVCAN makes an implicit assumption that the intra-vehicular network is secure; being situated on the edge between the secure vehicular network and the outside world, modems can be burdened with security enforcement activities. Any UDP traffic can be tunneled via DTLS (it's one of the DTLS's design goals) virtually without changes to the application layer, so this type can be used as the optimal point of abstraction above the two.

DTLS support in the experimental UDP forwarding type

---

.travis.yml
LICENSE
README.md
uavcan/diagnostic/32760.Record.1.0.uavcan
uavcan/node/32085.Heartbeat.1.0.uavcan
uavcan/node/434.GetTransportStatistics.0.1.uavcan
uavcan/node/ID.1.0.uavcan
uavcan/node/IOStatistics.0.1.uavcan
uavcan/node/port/431.List.0.1.uavcan
uavcan/node/port/432.GetInfo.0.1.uavcan
uavcan/node/port/433.GetStatistics.0.1.uavcan
uavcan/node/port/ID.1.0.uavcan
uavcan/node/port/ServiceID.1.0.uavcan
uavcan/node/port/SubjectID.1.0.uavcan
uavcan/pnp/32742.NodeIDAllocationDataMTU8.0.1.uavcan
uavcan/pnp/cluster/390.AppendEntries.1.0.uavcan
uavcan/pnp/cluster/391.RequestVote.1.0.uavcan
uavcan/register/384.Access.1.0.uavcan
uavcan/register/385.List.1.0.uavcan

A review is optional.
After this PR is merged, I propose to swap the branches so that the current master becomes the dedicated v0 branch and the current `uavcan-v1` becomes the new master. This is already done for PyUAVCAN: https://github.com/UAVCAN/pyuavcan/branches
Many data types are not yet stable, but thanks to the new versioning system we don't need to stabilize them in order to stabilize the whole namespace. Thanks, Kjetil.

Fix to #66 and minor clarifications

---

.vscode/spellright.dict
reg/drone/service/actuator/common/Status.0.1.uavcan
reg/drone/service/actuator/common/sp/_.0.1.uavcan
uavcan/file/405.GetInfo.0.1.uavcan
uavcan/file/406.List.0.1.uavcan
uavcan/file/407.Modify.1.0.uavcan
uavcan/file/408.Read.1.0.uavcan
uavcan/file/409.Write.1.0.uavcan
uavcan/node/430.GetInfo.1.0.uavcan
uavcan/node/434.GetTransportStatistics.0.1.uavcan
uavcan/node/435.ExecuteCommand.1.0.uavcan
uavcan/node/port/431.List.0.1.uavcan
uavcan/node/port/432.GetInfo.0.1.uavcan
uavcan/node/port/433.GetStatistics.0.1.uavcan
uavcan/pnp/8165.NodeIDAllocationData.2.0.uavcan
uavcan/pnp/cluster/390.AppendEntries.1.0.uavcan
uavcan/pnp/cluster/391.RequestVote.1.0.uavcan
uavcan/pnp/cluster/8164.Discovery.1.0.uavcan
uavcan/register/384.Access.1.0.uavcan
uavcan/register/385.List.1.0.uavcan
uavcan/time/510.GetSynchronizationMasterInfo.0.1.uavcan

About the diagnostic: https://forum.uavcan.org/t/data-type-extensibility-and-composition/827/20?u=pavel.kirienko
...which was implemented in: https://github.com/UAVCAN/pydsdl/pull/45/commits/e2816c746fb3c00f4089cb97da00ff416626433d
Example:
```
public_regulated_data_types/uavcan/file/405.GetInfo.0.1.uavcan:1: Request: Extent is not specified explicitly, defaulting to 170 bytes. To accept the default extent and silence this diagnostic, add the following line near the end of the definition: `@extent 170 * 8`
```
Some of the values are rounded to ((integer power of two) - 32) to optimize dynamic memory allocations for half-fit or buddy allocators which are expected to be commonly used in relevant applications. Other than that, the extent values are more or less the best guess.

Provide explicit @extent everywhere to silence diagnostics from PyDSDL

---

reg/drone/README.md
reg/drone/phy/acoustics/Note.0.1.uavcan
reg/drone/phy/electricity/Source.0.1.uavcan
reg/drone/srv/actuator/common/Feedback.0.1.uavcan
reg/drone/srv/actuator/common/Status.0.1.uavcan
reg/drone/srv/actuator/common/_.0.1.uavcan
reg/drone/srv/actuator/esc/_.0.1.uavcan
reg/drone/srv/actuator/servo/_.0.1.uavcan
reg/drone/srv/air_data_computer/_.0.1.uavcan
reg/drone/srv/battery/Status.0.1.uavcan
reg/drone/srv/battery/_.0.1.uavcan
reg/drone/srv/common/Heartbeat.0.1.uavcan
reg/drone/srv/common/Readiness.0.1.uavcan
reg/drone/srv/sensor/Status.0.1.uavcan

Fixes https://github.com/UAVCAN/public_regulated_data_types/issues/90
* Introduce minor clarifications and avoid overspecification.
* Propose fix to #90 by renaming without changing the semantics:
* Arming --> Readiness
* DISARMED --> STANDBY
* ARMED --> ENGAGED

[DS-015] Minor non-semantic adjustments

---

test.py
uavcan/diagnostic/8184.Record.1.1.uavcan
uavcan/file/405.GetInfo.0.2.uavcan
uavcan/file/406.List.0.2.uavcan
uavcan/file/407.Modify.1.1.uavcan
uavcan/file/408.Read.1.1.uavcan
uavcan/file/409.Write.1.1.uavcan
uavcan/file/Path.2.0.uavcan
uavcan/internet/udp/500.HandleIncomingPacket.0.2.uavcan
uavcan/internet/udp/8174.OutgoingPacket.0.2.uavcan
uavcan/metatransport/udp/Frame.0.1.uavcan
uavcan/node/435.ExecuteCommand.1.1.uavcan
uavcan/node/port/7510.List.0.1.uavcan
uavcan/node/port/SubjectIDList.0.1.uavcan
uavcan/register/384.Access.1.0.uavcan
uavcan/register/Name.1.0.uavcan

This is a follow-up to the previous discussion we had here and at the call. This change is not expected to introduce incompatibilities.
The new data types here are actually new versions of existing ones, where the old ones are marked deprecated.
The register API is updated without introducing new versions to avoid changing the fixed service-ID. This is wire-compatible provided that long register names are not used; if they are, requests will fail with deserialization error.

Enlarge arrays as discussed

---

uavcan/metatransport/can/Frame.0.1.uavcan
uavcan/metatransport/can/Frame.0.2.uavcan
uavcan/metatransport/ethernet/EtherType.0.1.uavcan
uavcan/metatransport/ethernet/Frame.0.1.uavcan
uavcan/metatransport/serial/Fragment.0.1.uavcan
uavcan/metatransport/serial/Fragment.0.2.uavcan
uavcan/metatransport/udp/DEPRECATED
uavcan/metatransport/udp/Endpoint.0.1.uavcan
uavcan/metatransport/udp/Frame.0.1.uavcan

This is a low-priority issue but it is cheap to address now. It will also unblock my ongoing background work on Yukon. Fixes #96 
- Remove timestamp from the transport frame encapsulation types because it violates the interface segregation principle.
- Replace `uavcan.metatransport.udp` with `uavcan.metatransport.ethernet` to enable more accurate modeling of the underlying media.
- Enlarge the serial fragment capacity to 2 KiB.

Address design issues in uavcan.metatransport

---

reg/drone/service/battery/Parameters.0.1.uavcan
reg/drone/service/battery/Parameters.0.2.uavcan
reg/drone/service/battery/Status.0.1.uavcan
reg/drone/service/battery/Status.0.2.uavcan

Main changes: 
- Adding individual cell voltages
- More comments on the parameters

Adding a v0.2 for the uavcan battery (BMS) parameters and status

---

uavcan/register/384.Access.1.0.uavcan

Introduce well-defined mapping between UAVCAN registers and environment variables. Given registers `uavcan.node.id` and `motor.inductance_dq`, one will be able to assign them values 42 and (0.14, 0.16) respectively by exporting environment variables `UAVCAN__NODE__ID=42` and `MOTOR__INDUCTANCE_DQ=0.14 0.16`.
This proposal is motivated by the recent experience with early v1 deployments and my own work on the Yukon backend rewrite (which itself is a UAVCAN-based system). Also, there is a weakly related thread about the possible role of UAVCAN as an IPC transport: https://forum.uavcan.org/t/will-libcanard-or-libuavcan-becomes-a-kind-of-software-bus-for-ipc/1119
While this is a minor change, its implications are significant. As I attempted to illustrate in …

Doc amendment for uavcan.register.Access: mapping between registers and environment variables

---

uavcan/pnp/8165.NodeIDAllocationData.2.0.uavcan
uavcan/pnp/8166.NodeIDAllocationData.1.0.uavcan

A UAVCAN v1 node is significantly less likely to be integrable into an end system without explicit prior configuration (whether manual or automated). This implies that after a PnP node is connected to the network for the first time, it will likely undergo additional configuration activities such as setting up subject-IDs and application-specific parameters (like PID gains). At this stage, most practical deployments will also commit the allocated node-ID to the non-volatile configuration to avoid reliance on the inherently non-deterministic behaviors of the PnP algorithm. This creates an unnecessary conflict with the PnP protocol specification that prohibits storing the allocated node-ID in the non-volatile configuration --- this limitation was justified for v0 but not for v1.
Existing …

Change wording in uavcan.pnp.NodeIDAllocationData to reflect the less static nature of UAVCAN v1

---

reg/drone/service/battery/Parameters.0.3.uavcan

As discussed in #112 
Adds the nominal voltage (the voltage that's typically on battery pack) to the reg.drone.battery.parameters message.
```
uavcan.si.unit.voltage.Scalar.1.0 nominal_voltage
```
Deprecates Parameters.0.2

reg.drone Battery parameters add nominal voltage

---

reg/drone/physics/kinematics/cartesian/PointStateVar.0.1.uavcan
reg/drone/physics/kinematics/geodetic/PointStateVar.0.1.uavcan
reg/drone/physics/kinematics/translation/Velocity3Var.0.2.uavcan

reg/drone: remove redundant timestamp in Velocity3Var

---

uavcan/node/port/7510.List.0.1.dsdl
uavcan/node/port/7510.List.1.0.dsdl
uavcan/node/port/ServiceIDList.0.1.dsdl
uavcan/node/port/ServiceIDList.1.0.dsdl
uavcan/node/port/SubjectIDList.0.1.dsdl
uavcan/node/port/SubjectIDList.1.0.dsdl

Closes #134; the other v0 types can be stabilized after the release.

Stabilize uavcan.node.port.List

---

uavcan/node/435.ExecuteCommand.1.3.dsdl

This PR allows for an output response in the form of a uint8 array, to allow for users to send commands and receive specific data, like device status or measurements back in a streamlined manner

Add output field in response

---

uavcan/node/435.ExecuteCommand.1.3.dsdl

This is a hotfix for #146 (tag @EliotRossRob). Currently it is not possible to enlarge the output field beyond 46 bytes due to the limited extent of the response.

Hotfix: reduce the extent of ExecuteCommand.1.3
